<?php

class GlobalVariables {

  const BOARD_ID = 42;

  public $do_spaces_access_key = 'DO801NRY7XC4LGZ6FCY3';

  public $do_spaces_secret_key = 'Ugaf8yEeRctKTDq71eXMRRaIS+eWFwpV6/4Hb149ThM';

  public $bucket_name = 'ib-42-photos';

  public $do_spaces_access_key_reduced = 'DO801HVYNWAAZ2UDV2KP';

  public $do_spaces_secret_key_reduced = 'Wc+yJUVCYzC3/haagvSQCUMzAlxkgdYX8IpNMLRx/A8';

  public $bucket_name_reduced = 'th-ib-42-photos';


  public $TOCKEN = 'Bearer 8b439b2251300ff9ac9065b67ada9850';

  public $select = "Appliances,ArchitecturalStyle,AssociationAmenities,AssociationFee,AssociationFeeFrequency,AssociationYn,AttachedGarageYn,AuctionTerms,Availability,BankOwnedYn,Basement,BathroomsFull,BathroomsHalf,BathroomsPartial,BathroomsTotalInteger,BeachAccess,BuildingAreaCalculated,BedroomsTotal,BuildingAreaDescription,BusinessName,BuildingAreaTotal,BuyerAgentFullName,BuyerAgentMlsId,BuyerOfficeMlsId,BuyerOfficeName,BuyerOfficePhone,City,CloseDate,ClosePrice,CoListAgentEmail,CoListAgentFullName,CoListAgentMlsId,CoListAgentPreferredPhone,CoListOfficeMlsId,CoListOfficeName,CommercialFeatures,CommunityFeatures,CondominiumDeckArea,CondominiumElevatorYn,CondominiumFloorPlan,CondominiumGarageType,CondominiumParkingTax,CondominiumParkingSpaceNo,CondominiumPetPoliciesYNUR,CondominiumUnitLevel,CondominiumYardYn,ContractStatusChangeDate,Cooling,Country,CountyOrParish,CropLandLeaseYn,CumulativeDaysOnMarket,CurrentPriceForStatus,CurrentUse,DaysOnMarket,DirectionFaces,Directions,DocumentsAvailable,ElectricOnPropertyDesc,ElementarySchool,ExistingLeaseType,ExteriorDescription,ExteriorFeatures,FarmAddlDwellingDesc,FarmType,FireplaceFeatures,FireplacesTotal,FloatingHomeBoatDockDesc,FuelDescription,FloatingHomeBoatDockYn,GarageSpaces,GarageType,GeoLocation,GrossIncome,Heating,HeatingYn,HighSchool,HotSheetDate,InteriorFeatures,InternetAddressDisplayYn,Latitude,ListAgentEmail,ListAgentFullName,ListAgentMlsId,ListAgentPreferredPhone,ListMainOfficeKeyNumeric,ListOfficeFax,ListOfficeMlsId,ListOfficeName,ListOfficePhone,ListPrice,ListingContractDate,ListingId,ListingKey,ListingService,ListingTerms,Longitude,LotFeatures,LotSizeAcres,LotSizeDimensions,LotSizeRange,LotSizeSquareFeet,MLSAreaMajor,ManufacturedHomeAllowedYn,MiddleOrJuniorSchool,MlsStatus,ModificationTimestamp,NeighborhoodFeatures,NewConstructionYn,NumberOfBuildings,NumberOfLots,NumberOfStallsFarm,NumberOfUnitsTotal,OccupancyTypes,OffMarketDate,OfferInstructions,OnMarketDate,OpenHouseYn,OriginalListPrice,OriginatingSystemKey,OriginatingSystemName,OtherEquipment,ParcelNumber,ParkingFeatures,ParkingTotal,PercentOwnership,Photo1URL,PhotosChangeTimestamp,PhotosCount,PhotosExistYn,PostalCode,PreviousListPrice,PriceType,PropertyAttachedYn,PropertyCondition,PropertySubType,PropertyType,PublicRemarks,RangeArea,RentAmount,RentIncludes,Roof,SaleIncludes,SecurityFeatures,SeniorCommunityYn,Sewer,ShortSalePendingDate,ShortSaleYn,SoilCondition,SoldPricePerSquareFeet,SourceSystemKey,StandardStatus,StateOrProvince,StatusChangeTimestamp,Storage,StoriesTotal,StreetDirPrefix,StreetDirSuffix,StreetName,StreetNumber,StreetSuffix,SubdivisionName,SupplementNumber,TaxAnnualAmount,TaxLegalDescription,TaxYear,UnitNumber,UnparsedAddress,UpperLevelAreaTotal,Utilities,ViewDescription,ViewYn,VineyardArea,VirtualTourURLUnbranded,VirtualTourURLUnbrandedYn,WaterSource,WaterfrontFeatures,WaterfrontYn,WindowFeatures,YearBuilt,Zoning,ListAgentKey,ListOfficeKey,ListMainOfficeKey,ListAgentKeyNumeric,PropertyRecordUpdateTimestamp,ManufacturerName,LandLeaseYn,FloorNumber,OpportunityZoneYn";


  public $class = [
    'CommercialProperty',
    'ResidentialProperty',
    'CondoProperty',
  ];

  public $baths = [
    'WashroomsType1' => 'WashroomsType1Pcs',
    'WashroomsType2' => 'WashroomsType2Pcs',
    'WashroomsType3' => 'WashroomsType3Pcs',
    'WashroomsType4' => 'WashroomsType4Pcs',
    'WashroomsType5' => 'WashroomsType5Pcs',
  ];

  public $wvFeatures = [
    'Beach Block',
    'BeachFront',
    'Beach Front',
    'Island',
    'Water Front',
    'Water View',
    'Boardwalk Front',
    'Bay Front',
  ];

  public $newWvFeatures = [
    'Beach Block',
    'Beach Front',
    'Beach Front',
    'Island',
    'Water Front',
    'Water View',
    'Boardwalk Front',
    'Bay Front',
  ];

  public $YOUR_API_KEY_21 = "AIzaSyB1BZAVsPFP-WdCF2UNhnpdNFb7rHED_qg";//board21



  public $suffixArray = [
    'ALLEE' => 'ALY',
    'ALLEY' => 'ALY',
    'ALLY' => 'ALY',
    'ALY' => 'ALY',
    'ANEX' => 'ANX',
    'ANNEX' => 'ANX',
    'ANNX' => 'ANX',
    'ANX' => 'ANX',
    'ARC' => 'ARC',
    'ARCADE' => 'ARC',
    'AV' => 'AVE',
    'AVE' => 'AVE',
    'AVEN' => 'AVE',
    'AVENU' => 'AVE',
    'AVENUE' => 'AVE',
    'AVN' => 'AVE',
    'AVNUE' => 'AVE',
    'BAYOO' => 'BYU',
    'BAYOU' => 'BYU',
    'BYU' => 'BYU',
    'BCH' => 'BCH',
    'BEACH' => 'BCH',
    'BEND' => 'BND',
    'BND' => 'BND',
    'BLF' => 'BLF',
    'BLUF' => 'BLF',
    'BLUFF' => 'BLF',
    'BLUFFS' => 'BLFS',
    'BLFS' => 'BLFS',
    'BOT' => 'BTM',
    'BTM' => 'BTM',
    'BOTTM' => 'BTM',
    'BOTTOM' => 'BTM',
    'BR' => 'BR',
    'BRNCH' => 'BR',
    'BRANCH' => 'BR',
    'BLVD' => 'BLVD',
    'BOUL' => 'BLVD',
    'BOULEVARD' => 'BLVD',
    'BOULV' => 'BLVD',
    'BRDGE' => 'BRG',
    'BRG' => 'BRG',
    'BRIDGE' => 'BRG',
    'BRK' => 'BRK',
    'BROOK' => 'BRK',
    'BROOKS' => 'BRKS',
    'BURG' => 'BG',
    'BG' => 'BG',
    'BURGS' => 'BGS',
    'BYP' => 'BYP',
    'BYPA' => 'BYP',
    'BYPAS' => 'BYP',
    'BYPASS' => 'BYP',
    'BYPS' => 'BYP',
    'CAMP' => 'CP',
    'CP' => 'CP',
    'CMP' => 'CP',
    'CANYN' => 'CYN',
    'CANYON' => 'CYN',
    'CNYN' => 'CYN',
    'CYN' => 'CYN',
    'CAPE' => 'CPE',
    'CPE' => 'CPE',
    'CAUSEWAY' => 'CSWY',
    'CAUSWA' => 'CSWY',
    'CSWY' => 'CSWY',
    'CEN' => 'CTR',
    'CENT' => 'CTR',
    'CENTER' => 'CTR',
    'CENTR' => 'CTR',
    'CENTRE' => 'CTR',
    'CNTER' => 'CTR',
    'CNTR' => 'CTR',
    'CTR' => 'CTR',
    'CENTERS' => 'CTRS',
    'CIR' => 'CIR',
    'CIRC' => 'CIR',
    'CIRCL' => 'CIR',
    'CIRCLE' => 'CIR',
    'CRCL' => 'CIR',
    'CIRCLES' => 'CIRS',
    'CRCLE' => 'CIR',
    'CLF' => 'CLF',
    'CLIFF' => 'CLF',
    'CLFS' => 'CLFS',
    'CLIFFS' => 'CLFS',
    'CLB' => 'CLB',
    'CLUB' => 'CLB',
    'COMMON' => 'CMN',
    'COMMONS' => 'CMNS',
    'COR' => 'COR',
    'CORNER' => 'COR',
    'CORNERS' => 'CORS',
    'CORS' => 'CORS',
    'COURSE' => 'CRSE',
    'CRSE' => 'CRSE',
    'COURT' => 'CT',
    'CT' => 'CT',
    'COURTS' => 'CTS',
    'CTS' => 'CTS',
    'COVE' => 'CV',
    'CV' => 'CV',
    'COVES' => 'CVS',
    'CREEK' => 'CRK',
    'CRK' => 'CRK',
    'CRESCENT' => 'CRES',
    'CRES' => 'CRES',
    'CRSENT' => 'CRES',
    'CRSNT' => 'CRES',
    'CREST' => 'CRST',
    'CROSSING' => 'XING',
    'CRSSNG' => 'XING',
    'XING' => 'XING',
    'CROSSROAD' => 'XRD',
    'CURVE' => 'CURV',
    'CURV' => 'CURV',
    'DALE' => 'DL',
    'DL' => 'DL',
    'DAM' => 'DM',
    'DIV' => 'DV',
    'DIVIDE' => 'DV',
    'DV' => 'DV',
    'DVD' => 'DV',
    'DR' => 'DR',
    'DRIV' => 'DR',
    'DRIVE' => 'DR',
    'DRV' => 'DR',
    'DRIVES' => 'DRS',
    'EST' => 'EST',
    'ESTATE' => 'EST',
    'EXPRESSWAY' => 'EXPY',
    'EXP' => 'EXPY',
    'EXPR' => 'EXPY',
    'EXPRESS' => 'EXPY',
    'EXPW' => 'EXPY',
    'EXPY' => 'EXPY',
    'FERRY' => 'FRY',
    'FRRY' => 'FRY',
    'FRY' => 'FRY',
    'FIELD' => 'FLD',
    'FLD' => 'FLD',
    'FIELDS' => 'FLDS',
    'FLDS' => 'FLDS',
    'FOREST' => 'FRST',
    'FRT' => 'FT',
    'FT' => 'FT',
    'FREEWAY' => 'FWY',
    'FREEWY' => 'FWY',
    'FRWY' => 'FWY',
    'FWY' => 'FWY',
    'FRWAY' => 'FWY',
    'GARDEN' => 'GDN',
    'GARDN' => 'GDN',
    'GRDEN' => 'GDN',
    'GRDN' => 'GDN',
    'GARDENS' => 'GDNS',
    'GDNS' => 'GDNS',
    'GRDNS' => 'GDNS',
    'GDN' => 'GDN',
    'GATEWAY' => 'GTWY',
    'GATEWY' => 'GTWY',
    'GATWAY' => 'GTWY',
    'GTWAY' => 'GTWY',
    'GTWY' => 'GTWY',
    'GREEN' => 'GRN',
    'GRN' => 'GRN',
    'GROVE' => 'GRV',
    'GROV' => 'GRV',
    'GRV' => 'GRV',
    'HARB' => 'HBR',
    'HARBOR' => 'HBR',
    'HARBR' => 'HBR',
    'HRBOR' => 'HBR',
    'HARBORS' => 'HBRS',
    'HBR' => 'HBR',
    'HAVEN' => 'HVN',
    'HVN' => 'HVN',
    'HT' => 'HT',
    'HTS' => 'HT',
    'HEIGHTS' => 'HT',
    'HIGHWAY' => 'HWY',
    'HIGHWY' => 'HWY',
    'HIWAY' => 'HWY',
    'HIWY' => 'HWY',
    'HWAY' => 'HWY',
    'HWY' => 'HWY',
    'HILL' => 'HL',
    'HL' => 'HL',
    'HLS' => 'HLS',
    'HILLS' => 'HLS',
    'HOLLOW' => 'HOLW',
    'HLLW' => 'HOLW',
    'HOLLOWS' => 'HOLW',
    'HOLW' => 'HOLW',
    'HOLWS' => 'HOLW',
    'ISLAND' => 'IS',
    'IS' => 'IS',
    'ISLND' => 'IS',
    'ISLANDS' => 'ISS',
    'ISLNDS' => 'ISS',
    'ISS' => 'ISS',
    'ISLE' => 'ISLE',
    'ISLES' => 'ISLE',
    'LAKE' => 'LK',
    'LK' => 'LK',
    'LKS' => 'LKS',
    'LAKES' => 'LKS',
    'LAND' => 'LAND',
    'LANDING' => 'LNDG',
    'LNDG' => 'LNDG',
    'LANE' => 'LN',
    'LN' => 'LN',
    'LGT' => 'LGT',
    'LIGHT' => 'LGT',
    'MALL' => 'MALL',
    'MEWS' => 'MEWS',
    'MOUNT' => 'MT',
    'MNT' => 'MT',
    'MT' => 'MT',
    'MNTAIN' => 'MTN',
    'MNTN' => 'MTN',
    'MOUNTAIN' => 'MTN',
    'MOUNTIN' => 'MTN',
    'MTIN' => 'MTN',
    'MTN' => 'MTN',
    'MOUNTAINS' => 'MTNS',
    'MTNS' => 'MTNS',
    'PARK' => 'PARK',
    'PARKS' => 'PARK',
    'PARKWAY' => 'PKWY',
    'PLACE' => 'PL',
    'PL' => 'PL',
    'PLAIN' => 'PLN',
    'PLN' => 'PLN',
    'PLAINS' => 'PLNS',
    'PLNS' => 'PLNS',
    'PLAZA' => 'PLZ',
    'PLZ' => 'PLZ',
    'PLZA' => 'PLZ',
    'POINT' => 'PT',
    'PT' => 'PT',
    'PORT' => 'PRT',
    'PRT' => 'PRT',
    'RANCH' => 'RNCH',
    'RANCHES' => 'RNCH',
    'RNCH' => 'RNCH',
    'RNCHS' => 'RNCH',
    'RAPID' => 'RPD',
    'RPD' => 'RPD',
    'RDG' => 'RDG',
    'RIDGE' => 'RDG',
    'RDGE' => 'RDG',
    'RIV' => 'RIV',
    'RIVER' => 'RIV',
    'RVR' => 'RIV',
    'RIVR' => 'RIV',
    'RD' => 'RD',
    'ROAD' => 'RD',
    'ROUTE' => 'RTE',
    'RTE' => 'RTE',
    'SHOAR' => 'SHR',
    'SHORE' => 'SHR',
    'SHR' => 'SHR',
    'SPRING' => 'SPG',
    'SPG' => 'SPG',
    'SPNG' => 'SPG',
    'SPRNG' => 'SPG',
    'SPGs' => 'SPGs',
    'SPRINGS' => 'SPGS',
    'SQUARE' => 'SQ',
    'SQ' => 'SQ',
    'STA' => 'STA',
    'STATION' => 'STA',
    'STN' => 'STA',
    'STRAVENUE' => 'STRA',
    'STRA' => 'STRA',
    'STREET' => 'ST',
    'STR' => 'ST',
    'ST' => 'ST',
    'TER' => 'TER',
    'TERR' => 'TER',
    'TERRACE' => 'TER',
    'TUNEL' => 'TUNL',
    'TUNL' => 'TUNL',
    'UN' => 'UN',
    'UNION' => 'UN',
    'VALLEY' => 'VLY',
    'VALLY' => 'VLY',
    'VLLY' => 'VLY',
    'VLY' => 'VLY',
    'VIEW' => 'VW',
    'VW' => 'VW',
    'VILL' => 'VLG',
    'VILLAGE' => 'VLG',
    'VLG' => 'VLG',
    'VILLE' => 'VL',
    'VL' => 'VL',
    'WALK' => 'WALK',
    'VIS' => 'VIS',
    'VIST' => 'VIS',
    'VISTA' => 'VIS',
    'WALL' => 'WALL',
    'WAY' => 'WAY',
    'WY' => 'WAY',
    'WELLS' => 'WLS',
    'WLS' => 'WLS',
    'TRAIL' => 'TRL',
    'TRL' => 'TRL',
    'TRAILER' => 'TRLR',
    'TRLR' => 'TRLR',
    'TRACK' => 'TRACK',
    'STREAM' => 'STRM',
    'STRM' => 'STRM',
  ];

  public $prefixArray = [
    'NORTH' => 'N',
    'NORTHEAST' => 'NE',
    'NORTHWEST' => 'NW',
    'SOUTHEAST' => 'SE',
    'SOUTHWEST' => 'SW',
    'EAST' => 'E',
    'WEST' => 'W',
    'SOUTH' => 'S',
  ];

  //    public $workaHost = "localhost";
  //    public $workaUser = "root";
  //    public $workaPassword = "";
  //    public $workaPort = 3306;
  public $dbHost = "207.246.89.83";

  public $dbUser = "idxwriter";

  public $dbPassword = "vtergWvg3h3mSH9b";

  public $dbPort = 3306;

  //    public $dbHost = "localhost";
  //    public $dbUser = "root";
  //    public $dbPassword = "";
  //    public $dbPort = 3306;
  public $workaHost = "144.202.9.86";

  public $workaUser = "idxwriter";

  public $workaPassword = "YXu2BdgEfqbyd8Vm";

  public $workaPort = 3306;

  public $dbCharset = 'utf8mb4';

  //    public $activeDb = 'idx_newjersey';
  public $activeDb = 'idxboost_b42_db';

  public $historyDb = 'idxboost_b42_history';

  public $options = [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES => FALSE,
  ];

  public $states = [
    'Alberta' => 'AB',
    'Ontario' => 'ON',
    'New Brunswick' => 'NB',
  ];

  public $statesName = [
    'OR' => 'Oregon',
    'WA' => 'Washington',
  ];

}